### ISSUE TITLE
Rocket M5 Titanium Issues

### ISSUE THREAD

**Issue by theklap** [Ubiquiti-App/UNMS#78] opened 2017-09-22 13:57 UTC
I have 17 devices connected to our UNMS instance.  The only Rocket M5 Titanium we have will not connect to the UNMS instance.  The full log from running sudo udapi-bridge -v UNMS-KEY on the device is attached.

Some of the interesting bits from the log:
2017-09-22 08:49:09 ERROR ca_cert_load_all_file: error scanning /etc/persistent/udapi-bridge: No such file or directory
2017-09-22 08:49:09 ERROR failed to write CA certificates to temporary file
2017-09-22 08:49:09 DEBUG Unable to load SSL Client certs file from /tmp/udapi-bridge-ca.pem.ofZvkv -- client ssl isn't going to work
2017-09-22 08:49:12 INFO  peer closed connection (status 1000): Connection terminated by UNMS because connect event expected

[R5T.txt](https://github.com/Ubiquiti-App/UNMS/files/1324733/R5T.txt)

**Comment by celticguy42** [comment] 2017-10-18 19:36
Any updates on this issue?  We have 6 Rocket M5 Titaniums with this very issue.

2017-10-18 14:35:24 INFO  udapi-bridge 0.0.9-watchdog-fix3-no-git
2017-10-18 14:35:24 DEBUG Initial logging level 15
2017-10-18 14:35:24 DEBUG Libwebsockets version: 2.2.0 buildd@builder-
2017-10-18 14:35:24 DEBUG IPV6 not compiled in
2017-10-18 14:35:24 DEBUG libev support not compiled in
2017-10-18 14:35:24 DEBUG libuv support not compiled in
2017-10-18 14:35:24 DEBUG  Threads: 1 each 1024 fds
2017-10-18 14:35:24 DEBUG  mem: platform fd map:  4096 bytes
2017-10-18 14:35:24 DEBUG  Compiled with OpenSSL support
2017-10-18 14:35:24 DEBUG Doing SSL library init
2017-10-18 14:35:24 DEBUG Creating Vhost 'default' port -1, 1 protocols, IPv6 off
2017-10-18 14:35:24 DEBUG  mem: per-conn:          448 bytes + protocol rx buf
2017-10-18 14:35:24 DEBUG  canonical_hostname = ap1
2017-10-18 14:35:24 INFO  connecting to unms:443
2017-10-18 14:35:24 DEBUG lws_client_connect_2: address unms
2017-10-18 14:35:24 DEBUG lws_client_connect_2: address unms
2017-10-18 14:35:24 DEBUG lws_ssl_client_connect2: SSL_connect says -1
2017-10-18 14:35:24 DEBUG lws_ssl_client_connect2: SSL_connect says 1
2017-10-18 14:35:24 INFO  connection established
2017-10-18 14:35:24 DEBUG unms tx:
{
  "protocol":"2.0",
  "type":"event",
  "timestamp":1508355324872,
  "id":"7cc254f81be8e78d",
  "name":"connect",
  "__associated_data":"\u0004\u0018▒L▒7",
  "model":"R5T"
}
2017-10-18 14:35:24 INFO  peer closed connection (status 1000): Connection terminated by UNMS because connect event expected
2017-10-18 14:35:24 INFO  connection closed
2017-10-18 14:35:26 INFO  connecting to unms:443
2017-10-18 14:35:26 DEBUG lws_client_connect_2: address unms
2017-10-18 14:35:26 DEBUG lws_client_connect_2: address unms
2017-10-18 14:35:26 DEBUG lws_ssl_client_connect2: SSL_connect says -1
2017-10-18 14:35:26 DEBUG lws_ssl_client_connect2: SSL_connect says 1
2017-10-18 14:35:26 INFO  connection established
2017-10-18 14:35:26 DEBUG unms tx:
{
  "protocol":"2.0",
  "type":"event",
  "timestamp":1508355326490,
  "id":"765a2e63339fc99a",
  "name":"connect",
  "__associated_data":"\u0004\u0018▒L▒7",
  "model":"R5T"
}
2017-10-18 14:35:26 INFO  peer closed connection (status 1000): Connection terminated by UNMS because connect event expected
2017-10-18 14:35:26 INFO  connection closed

**Comment by celticguy42** [comment] 2017-10-18 19:49
This probably explains it:

2017-10-18T19:35:26Z	unms	{"source":"stdout","log":"171018/193526.508, [log,info,ws] data: WS - connect: Device model 'R5T' not supported","container_id":"5ba503e2fb47565bbdd8d366145db58cc720e470b2b694b204fc379537d3dc3b","container_name":"/unms"}

Any idea when the R5 Titanium will be supported?

**Comment by jaroklima** [comment] 2017-10-19 11:00
Thank you for reporting the issue, we are able to reproduce it and will work on a fix.

**Comment by ubnt-michals** [comment] 2018-01-15 07:21
Fixed in the latest release

**Closed by ubnt-michals** 2018-01-15 07:21 UTC
Labels: bug
