### ISSUE TITLE
Updated SSL cert changed device key

### ISSUE THREAD

**Issue by secesh** [Ubiquiti-App/UNMS#69] opened 2017-08-25 18:31 UTC
Updating SSL certificate (switched from self-signed to lets encrypt) seems to have caused the UNMS device key to change. Devices were enrolled before this change, which caused loss of access to those devices.

**Comment by jaroklima** [comment] 2017-09-11 08:38
@secesh thank you for reporting the issue.

I don't think that your UNMS key has changed. The key that you see on the device side is different from the key that you see in UNMS because after the initial handshake, each device automatically gets a unique new key. This has nothing to do with SSL certificates.

The fact that your devices cannot connect probably IS related to the SSL key change, just not to the UNMS key. What error messages do you see in the [device logs](https://github.com/Ubiquiti-App/UNMS/wiki/Discovery-Troubleshooting#where-to-find-logs-on-the-device)?

(If you just want to fix the issue quickly, you can hit "refresh" next to each device in the list and connect them again using the key that you see in UNMS)

**Comment by secesh** [comment] 2017-09-12 14:13
I wasn't looking at the key on the device. I was looking at the key in the UNMS portal used for manually enrolling devices. I think part of the problem might be related to docs, which don't indicate use of ```--update``` in the SSL section. I would think, though, that this key should **never** change without at least a confirmation prompt.

**Comment by jaroklima** [comment] 2017-09-12 14:37
The `--update` parameter tells the installation script to reuse the arguments (like `--ssl-cert`) from last time. It should have no effect on the key in the UNMS connection string. How did you 'switch from self-signed to lets encrypt'? Did you install with the `--ssl-cert-*` arguments first and then reinstalled without, or did you change the UNMS hostname/IP in the UNMS settings?

**Comment by secesh** [comment] 2017-09-22 21:59
I first installed UNMS following docs wiki. This is copy/paste from wiki:
```bash
curl -fsSL https://raw.githubusercontent.com/Ubiquiti-App/UNMS/master/install.sh > /tmp/unms_install.sh && sudo bash /tmp/unms_install.sh
```
Things ran fine for some days. Then I wrote a script to update LE keys in the spirit of the SSL section from docs wiki (this just attempted to install/update the keys, which are gotten elsewhere):
```bash
curl -fsSL https://raw.githubusercontent.com/Ubiquiti-App/UNMS/master/install.sh > /tmp/unms_install.sh
rm -rf /home/unms/LE/
cp -R /home/USER/.acme.sh/FQDN/ /home/unms/LE/
chown unms /home/unms/LE
bash /tmp/unms_install.sh --ssl-cert-dir /home/unms/LE --ssl-cert fullchain.cer --ssl-cert-key FQDN --ssl-cert-ca ca.cer
```

**Comment by jaroklima** [comment] 2017-09-25 09:14
I am sorry, but I cannot reproduce the issue. Also, from our code it's clear that a new key is only generated when an existing key (or any other settings) cannot be found in the database.

The UNMS connection string is in the form

    https://<hostname>:<port>+<aesKey>[+allowSelfSignedCertificate]

The `aesKey` part always stays the same. The `+allowSelfSignedCertificate` suffix can change based on the SSL certificate and the `hostname:port` part changes based on `Hostname/IP` in the UNMS settings, is this what you meant?

**Comment by secesh** [comment] 2017-09-25 12:48
The aesKey is the portion that changed. If I know the old key, is there any way to put it back?

**Comment by jaroklima** [comment] 2017-09-27 13:48
Why would you want to put it back? After a device connects for the first time (using the 'universal' key from UNMS), it gets a new, 'personal' key and it doesn't matter anymore what the universal key is. The universal key is only used once per device. If you put it back, your device still won't be able to reconnect. 

Also, if your universal UNMS key changed after you changed the SSL cert, it wouldn't cause your devices to disconnect.

The only thing I can think of that would cause your universal UNMS key to change and your devices to disconnect would be a deleted database.

**Comment by secesh** [comment] 2017-09-27 13:55
I want to regain control of devices that were enrolled before the key changed. I don't think we're understanding each other.

**Comment by jaroklima** [comment] 2017-09-27 15:02
I think we are, but unfortunately restoring the old key in UNMS won't help you. If your devices aren't reconnecting, it is not because the UNMS key has changed. You can follow our troubleshooting guides ([1](https://github.com/Ubiquiti-App/UNMS/wiki/Discovery-Troubleshooting#where-to-find-logs-on-the-device), [2](https://github.com/Ubiquiti-App/UNMS/wiki/Device-log-Troubleshooting)) to figure why a device fails to connect, but from what I read it seems that you have somehow deleted your database and will have to connect the devices again, with the new UNMS key.

**Comment by secesh** [comment] 2017-09-27 15:22
I strongly disagree -- I did not (accidentally or otherwise) delete anything related to UNMS. If something was inadvertently deleted, it was done by the UNMS install script or some other component of the UNMS software.

I am very disappointed with this experience and concerned for the stability of UNMS software moving forward. This is a critical concern because there is a feature of UNMS where access to the router can be turned off. In this case, the router can only be managed through UNMS and access to the router can be lost when a UNMS key changes unexpectedly.

**Comment by jaroklima** [comment] 2017-09-27 16:50
I'm sorry, I meant to say 'the database got deleted', didn't mean to imply that it couldn't be UNMS's fault.

-----------------
You can manually set the UNMS key by updating the value in the database:
```
sudo docker exec -ti unms-redis redis-cli
get nms:nms
```
This will return an escaped JSON string. You can modify the aesKey part and insert the whole string back into the database:
```
set nms:nms <new string>
```

This won't help you reconnect your devices unless they are EdgeRouters with FW 1.9.7alphaX or lower or airMAX with FW 8.3.0.

--------------
To list the device-specific keys that UNMS generated for each device:
```
sudo docker exec -u postgres -it unms-postgres psql
\c unms
select * from mac_aes_key;
\q
```
This will return an (id, mac, key, status) for each of the devices registered in UNMS.
You can compare the UNMS keys from your devices to the keys in this list. If they match, then the keys aren't the problem.

**Comment by radekskrivan** [comment] 2018-01-18 13:44
Closing this older ticket. If the issue persists please let us know.

**Closed by radekskrivan** 2018-01-18 13:44 UTC
Labels: bug
