### ISSUE TITLE
UNMS Backup Failed.

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#5] opened 2017-01-02 16:11 UTC
When within a OLT Device that is assigned, i click backup, everything seems to be working on the front end, and then the follow below happens. 

![screen shot 2017-01-02 at 11 11 26 am](https://cloud.githubusercontent.com/assets/14851974/21592534/3d9f211c-d0dc-11e6-9427-6d8be0df7b96.png)

Screen Capture
![screen shot 2017-01-02 at 11 07 25 am](https://cloud.githubusercontent.com/assets/14851974/21592494/d9b78e6e-d0db-11e6-8524-6382becd5010.png)

Code Responce 
170102/161953.230, [response] https://e327f1c7d6fd:8443: get /v2.1/devices/a862ac4e-d374-41da-8dc0-581d319200b8/backups {} 200 (10ms)
170102/161953.388, [ops] memory: ****Mb, uptime (seconds): 978.956, load: [0.013671875,0.00732421875,0]
170102/161954.739, [response] https://e327f1c7d6fd:8443: get /v2.1/logs/unread {"timestamp":"1483373962487"} 200 (23ms)
170102/161954.747, [response] https://e327f1c7d6fd:8443: get /v2.1/outages/unread {"timestamp":"2017-01-02T16:19:22.488Z"} 200 (21ms)
170102/161954.751, [response] https://e327f1c7d6fd:8443: get /v2.1/devices/olts/a862ac4e-d374-41da-8dc0-581d319200b8 {} 200 (20ms)
170102/161956.250, [response] https://e327f1c7d6fd:8443: get /v2.1/devices/a862ac4e-d374-41da-8dc0-581d319200b8/backups {} 200 (9ms)
170102/161956.586, [ops] memory: ****Mb, uptime (seconds): 982.154, load: [0.01220703125,0.0068359375,0]
170102/161958.388, [ops] memory: ****Mb, uptime (seconds): 983.957, load: [0.01220703125,0.0068359375,0]
170102/161959.228, [response] https://e327f1c7d6fd:8443: get /v2.1/devices/a862ac4e-d374-41da-8dc0-581d319200b8/backups {} 200 (9ms)
170102/161959.740, [response] https://e327f1c7d6fd:8443: get /v2.1/logs/unread {"timestamp":"1483373962487"} 200 (20ms)
170102/161959.743, [response] https://e327f1c7d6fd:8443: get /v2.1/outages/unread {"timestamp":"2017-01-02T16:19:22.488Z"} 200 (19ms)
170102/161959.751, [response] https://e327f1c7d6fd:8443: get /v2.1/devices/olts/a862ac4e-d374-41da-8dc0-581d319200b8 {} 200 (17ms)
170102/161959.945, [log,error] data: WS - client: 4fe1e061-dfbb-41f7-b806-78d6cfb5a835 timeout: 8152f72f-5a3b-484c-a39c-d5fb11c1c317:backupConfig
170102/161934.394, [error] message: Rejected promise stack: Error: Rejected promise
    at onError (/home/app/unms/node_modules/hapi/lib/response.js:474:25)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
170102/161934.394, [response] https://e327f1c7d6fd:8443: post /v2.1/devices/a862ac4e-d374-41da-8dc0-581d319200b8/backups {} 500 (25567ms)
170102/162002.231, [response] https://e327f1c7d6fd:8443: get /v2.1/devices/a862ac4e-d374-41da-8dc0-581d319200b8/backups {} 200 (9ms)

Edit: 

When the backup fails the OLT device icon within UNMS turns "RED". The OLT should only be turning red if the Heartbeat is lost (Ping) This can cause some confusion when issues like this happen.

![screen shot 2017-01-02 at 4 16 00 pm](https://cloud.githubusercontent.com/assets/14851974/21596289/4a4672c8-d107-11e6-9799-c51a6a5b1c39.png)

![screen shot 2017-01-02 at 4 20 36 pm](https://cloud.githubusercontent.com/assets/14851974/21596296/71d7de62-d107-11e6-8287-ac0474833c50.png)

**Comment by Dstahl0** [comment] 2017-01-02 21:17
Still seeing it with 0.2.5-Alpha.

**Comment by jflidr** [comment] 2017-01-02 22:24
> When the backup fails the OLT device icon within UNMS turns "RED". The OLT should only be turning red if the Heartbeat is lost (Ping) This can cause some confusion when issues like this happen.
Yes, there is a bug. UNMS lost connection with OLT during downloading config. I will test FW 0.2.5alpha and let you know.

**Comment by jflidr** [comment] 2017-01-08 23:16
@Dstahl0 Could you please retest this bug with OLT FW 0.2.6 + UNMS 0.7.9? It seems to be ok. Thanks a lot.

**Comment by Dstahl0** [comment] 2017-01-08 23:18
Do you have the url for 0.2.6 OLT? if so email me the url would be fine or pm me at DStahl on the community.

**Comment by MartinStrbacka** [comment] 2017-01-08 23:20
@Dstahl0 Here is the 0.2.6. OLT Firmware https://drive.google.com/open?id=0BwHKXNHD5BGmdlViU0ViVDNnVVE

**Comment by Dstahl0** [comment] 2017-01-08 23:21
i got the file downloaded, we can remove the url now :)

**Comment by Dstahl0** [comment] 2017-01-08 23:33
This is what i get.

170108/022924.485, [log,error] data: WS - client: a862ac4e-d374-41da-8dc0-581d319200b8 c714037d-fb67-4cef-87cc-93e937363ffa timeout: 78a93929-f779-4cfe-a05f-b6b4e4bebcac:backupConfig
170108/022858.921, [error] message: Rejected promise stack: Error: Rejected promise
    at onError (/home/app/unms/node_modules/hapi/lib/response.js:474:25)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
170108/022858.921, [response] https://a7416a600ab3:8443: post /v2.1/devices/a862ac4e-d374-41da-8dc0-581d319200b8/backups {} 500 (25605ms)
170108/022926.461, [ops] memory: 116Mb, uptime (seconds): 41997.425, load: [0.02099609375,0.02734375,0]




![screen shot 2017-01-08 at 6 32 30 pm](https://cloud.githubusercontent.com/assets/14851974/21754568/f5f946d6-d5d0-11e6-9cc3-9b6ecd4a4b1a.png)

![screen shot 2017-01-08 at 6 32 48 pm](https://cloud.githubusercontent.com/assets/14851974/21754569/f93b7634-d5d0-11e6-893f-498f07cf2db8.png)

**Comment by jflidr** [comment] 2017-01-08 23:45
@Dstahl0 Thank you for retest. Could you send me backup config from OLT UI (System -> Configuration Management & Device Maintenance -> Download backup config file: -> Download).

**Comment by Dstahl0** [comment] 2017-01-08 23:47
Thanks @jflidr , Do you have a email address i can send it to?

**Comment by jflidr** [comment] 2017-01-08 23:51
@Dstahl0 You can use: jindrich.flidr@ubnt.com, thanks.

**Comment by Dstahl0** [comment] 2017-01-08 23:59
Email has been sent.

**Comment by Dstahl0** [comment] 2017-01-09 01:15
@jflidr  i connected another OLT device and using the same UNMS Server, it seems to be working for this new OLT.

![screen shot 2017-01-08 at 8 13 30 pm](https://cloud.githubusercontent.com/assets/14851974/21755253/f676515e-d5de-11e6-8a71-f1bc82514ba9.png)

**Comment by jflidr** [comment] 2017-01-09 10:43
@Dstahl0 We can finally reproduce this bug. The problem is that that backup is quite big because it includes result of "generate tech-support archive". We will fix it in version 0.7.11.

**Comment by Dstahl0** [comment] 2017-01-09 13:52
Sounds Good, i'm glad you could reproduce this bug.

Thanks @jflidr

**Comment by jflidr** [comment] 2017-01-14 11:15
UNMS part is fixed in UNMS version 0.7.10. It is necessary to have FW 0.2.7 for OLT or 1.9.2alpha1 for EdgeRouters.

**Closed by jflidr** 2017-01-14 11:15 UTC

**Comment by Dstahl0** [comment] 2017-01-14 16:41
Thank you @jflidr  👍
