### ISSUE TITLE
../crm/client-zone/support Contact Us Email Address incorrect

### ISSUE THREAD

**Issue by BzerkSkemer** [Ubiquiti-App/UNMS#177] opened 2019-10-18 06:45 UTC
It appears that when accessing ../crm/client-zone/support the primary organisation email address is shown and not the clients selected organisation email address. All other details on the page update from the correct organisation.
Thank you :)

**Comment by UBNT-Petr** [comment] 2019-10-23 16:03
we will look into it, it should be fixed very soon. Please, note that you can use the UNMS community forum for bug reporting or suggestions. The forum is maintained by the whole support team, so you will get prompt responses.

**Comment by UBNT-Petr** [comment] 2019-10-25 08:16
@BzerkSkemer we found out, it works as intended. By default, the support email is shown in the Client Zone (check the support email in System -> Settings -> Mailer). Only if it's empty, the organization email is used as a fallback.

**Closed by UBNT-Petr** 2019-10-25 08:16 UTC
